### PR TITLE
test: add integration tests for numeric

### PR DESCRIPTION
**Pull request by olavloite**
Adds integration tests for `NUMERIC` data type.

### CODE REVIEW

**Comment by olavloite** [comment]
@skuruppu Could it be that the emulator does not yet support `NUMERIC`?

**Review by skuruppu — APPROVED** [review]

**Comment by skuruppu** [comment]
@olavloite yes, Emulator doesn't yet support NUMERIC :( So you will have to maintain a separate copy of the schema for emulator vs non-emulator tests and the skips for the numeric-specific tests. It's a bit messy but the emulator support is coming soon so we can clean it up quickly.

**Comment by olavloite** [comment]
(The build failure for `Kokoro - Test: Samples Java 8` is an unrelated transient `[ERROR] error reading /root/.m2/repository/com/google/protobuf/protobuf-java/3.12.4/protobuf-java-3.12.4.jar; zip file is empty` error)

**Comment by olavloite** [comment]
> @olavloite yes, Emulator doesn't yet support NUMERIC :( So you will have to maintain a separate copy of the schema for emulator vs non-emulator tests and the skips for the numeric-specific tests. It's a bit messy but the emulator support is coming soon so we can clean it up quickly.

I've made the integration test check whether it is running on the emulator, and based on that, it decides whether or not to include a `NUMERIC` column.

**Pull request merged**
