### PR TITLE
deps: test building with newer library version

### PR DESCRIPTION
**Pull request by suztomo**
No need to review.

### CODE REVIEW

**Comment by suztomo** [comment]
```
Error:  /home/runner/work/java-spanner/java-spanner/proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/ReplicaInfo.java:[450,48] cannot find symbol
  symbol:   method isStringEmpty(java.lang.Object)
  location: class com.google.protobuf.GeneratedMessageV3
Error:  /home/runner/work/java-spanner/java-spanner/proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/ReplicaInfo.java:[470,48] cannot find symbol
  symbol:   method isStringEmpty(java.lang.Object)
  location: class com.google.protobuf.GeneratedMessageV3
Error:  /home/runner/work/java-spanner/java-spanner/proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/Instance.java:[819,48] cannot find symbol
  symbol:   method isStringEmpty(java.lang.Object)
  location: class com.google.protobuf.GeneratedMessageV3
Error:  /home/runner/work/java-spanner/java-spanner/proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/Instance.java:[822,48] cannot find symbol
  symbol:   method isStringEmpty(java.lang.Object)
  location: class com.google.protobuf.GeneratedMessageV3
```

**Comment by suztomo** [comment]
"Kokoro - Test: Integration" due to certain setup missing:

```
com.google.cloud.spanner.InstanceNotFoundException:
NOT_FOUND: com.google.cloud.spanner.InstanceNotFoundException: NOT_FOUND: io.grpc.StatusRuntimeException: NOT_FOUND: Instance not found: projects/gcloud-devel/instances/spanner-testing-west1
resource_type: "type.googleapis.com/google.spanner.admin.instance.v1.Instance"
resource_name: "projects/gcloud-devel/instances/spanner-testing-west1"
description: "Instance does not exist."

	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:279)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:61)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:181)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:110)
	at com.google.cloud.spanner.testing.RemoteSpannerHelper.createTestDatabase(RemoteSpannerHelper.java:130)
	at com.google.cloud.spanner.testing.RemoteSpannerHelper.createTestDatabase(RemoteSpannerHelper.java:96)
	at com.google.cloud.spanner.connection.ITAbstractSpannerTest.setup(ITAbstractSpannerTest.java:222)
```

**Comment by rajatbhatta** [comment]
@suztomo: We were using projects/gcloud-devel/instances/spanner-testing-west1 as instance for testing in [6.4.4-sp](https://github.com/googleapis/java-spanner/blob/6.4.4-sp/google-cloud-spanner/pom.xml#L73), but have now moved to projects/gcloud-devel/instances/spanner-testing-east1 ([link](https://github.com/googleapis/java-spanner/blob/main/google-cloud-spanner/pom.xml#L21)).

projects/gcloud-devel/instances/spanner-testing-west1 instance no longer exists, which is why we are getting the InstanceNotFoundException.

**Comment by suztomo** [comment]
Thank you. Now it's marked green.

Screen Shot 2022-09-23 at 11 28 52 AM

**Pull request closed without merging**
