### PR TITLE
fix: add missing native image test command to build script

### PR DESCRIPTION
**Pull request by mpeddada1**

### CODE REVIEW

**Review by ansh0l — APPROVED** [review]
lgtm, adding do not merge label

**Review by suztomo — APPROVED** [review]

**Comment by mpeddada1** [comment]
Thanks for the review @ansh0l and @suztomo! Would it be okay to merge this PR? The Graalvm job is currently not running in the repo so adding this script will help with debugging https://github.com/googleapis/java-spanner/pull/1811

**Comment by ansh0l** [comment]
Closing since native image changes have been released with https://github.com/googleapis/java-spanner/pull/1878

**Comment by ansh0l** [comment]
Closing since native image changes have been released with https://github.com/googleapis/java-spanner/pull/1878

**Pull request closed without merging**
