### PR TITLE
test: skip backup test if it takes too long

### LINKED ISSUE #683: spanner.it.ITBackupTest: testBackups failed
Note: #542 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: d093089bbc37d02b5e66305fab04e02e6a9c3a67
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/6beae198-3c20-40a1-a602-fa4b82353517), [Sponge](http://sponge2/6beae198-3c20-40a1-a602-fa4b82353517)
status: failed
<details><summary>Test output</summary><br><pre>com.google.cloud.spanner.SpannerException: DEADLINE_EXCEEDED: Backup1 still not finished. Test is giving up waiting for it.
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:259)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:59)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:54)
	at com.google.cloud.spanner.it.ITBackupTest.testBackups(ITBackupTest.java:293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
</pre></details>

### PR DESCRIPTION
**Pull request by olavloite**
Fixes #683

### CODE REVIEW

**Comment by thiagotnunes** [comment]
I am not sure this is the best way to tackle this flakiness, because the backup not finishing might be an indication of a real problem. This test would then be non-deterministic in this case, we would not know if it was skipped due to a real failure or due to taking too long. 

I am wondering if we should not remove this test entirely.

**Comment by olavloite** [comment]
> I am not sure this is the best way to tackle this flakiness, because the backup not finishing might be an indication of a real problem. This test would then be non-deterministic in this case, we would not know if it was skipped due to a real failure or due to taking too long.
> 
> I am wondering if we should not remove this test entirely.

We could also consider assigning it a separate category that is skipped by default, but that is included in nightly (or other specific) builds.

**Comment by thiagotnunes** [comment]
@olavloite I think that works, thanks for fixing it

**Review by thiagotnunes — APPROVED** [review]

**Comment by olavloite** [comment]
@thiagotnunes I'm afraid that this works locally, but not in CI at the moment. It complains about two things:
1. Apparently the `integration.cfg` file is a generated file. Do you know how we can create/edit the template for it?
1. Adding an environment variable to the build is also not allowed by default, so the integration test fails with the following error:
```
[15:32:49][ERROR] Found un-allowed variables:

SKIP_BACKUP_INTEGRATION_TESTS="true" (No matching key in allowed env vars)
```

Any idea how to fix that?

**Comment by thiagotnunes** [comment]
@olavloite ah ok, there is a file I can modify to allow for that env var. There is one env var that is already defined that maybe we can use: `INTEGRATION_TEST_ARGS`. Could you try using that one first?

**Comment by olavloite** [comment]
> @olavloite ah ok, there is a file I can modify to allow for that env var. There is one env var that is already defined that maybe we can use: `INTEGRATION_TEST_ARGS`. Could you try using that one first?

I tried with `INTEGRATION_TEST_ARGS`, but that seems to be reserved for other usages. Setting a value for it in the `integration.cfg` file for pre-submit checks causes the following error:

```
[ERROR] Unknown lifecycle phase "SKIP_BACKUP_INTEGRATION_TESTS". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
```

**Comment by olavloite** [comment]
I'm inclined to close this PR as the backup tests have started being successful again lately. It might be that these problems were a side effect of the problems that we were seeing with `RESOURCE_EXHAUSTED` errors for too many administrative requests. @thiagotnunes WDYT?

**Comment by thiagotnunes** [comment]
@olavloite I agree

**Pull request closed without merging**
