### PR TITLE
chore: mark native image checks as required

### PR DESCRIPTION
**Pull request by mpeddada1**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-spanner/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> ☕️

If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).

### CODE REVIEW

**Comment by ansh0l** [comment]
Hey @mpeddada1 , would you have any stats on how this new presubmit is doing? As in, how often was it failing when any of the merges got done previously? If not, I would want to monitor for an additional month or so before making it mandatory.

**Comment by mpeddada1** [comment]
Hey @ansh0l, just looked into the [recently merged PRs](https://github.com/googleapis/java-spanner/pulls?q=is%3Apr+is%3Aclosed) in this repository. I haven't observed failures specific to native image compilation so far but I have noticed the `ITInstanceAdminTest#updateInstance` and `ITInstanceAdminTest#updateInstanceViaEntity` tests in these presubmits being pretty flaky. I'm wondering if this could be related to https://github.com/googleapis/java-spanner/issues/1626?

**Comment by ansh0l** [comment]
cc @rajatbhatta to take a look at the related issue

**Comment by mpeddada1** [comment]
Thanks @ansh0l! are we considering #1626 as a prerequisite to marking these checks as required?

**Comment by ansh0l** [comment]
Thanks @mpeddada1 ! We can monitor for another couple of weeks, and then merge this.

**Comment by mpeddada1** [comment]
Hey @ansh0l @rajatbhatta looks like we haven't had a chance to merge this PR in yet. Could we get your review on this? It'll help us gate releases on the compatibility with native image compilation.

**Review by rajatbhatta — APPROVED** [review]

**Comment by rajatbhatta** [comment]
Hi @mpeddada1: Merged this PR. Thank you!

**Comment by mpeddada1** [comment]
Thank you @rajatbhatta!

**Pull request merged**
