### PR TITLE
fix: Correct recording values in opencensus measureMap in HeaderInterceptor

### PR DESCRIPTION
**Pull request by KiranmayiB**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-spanner/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> ☕️

If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).

### CODE REVIEW

**Comment by thiagotnunes** [comment]
@KiranmayiB can you explain how does this change solve the issue we are seeing?

**Comment by KiranmayiB** [comment]
> @KiranmayiB can you explain how does this change solve the issue we are seeing?

Here, the code puts a value into the measureMap twice and says record twice. That is causing the crash as we cannot put anything into the measureMap after we say record. So i think the second time when it tried to put a value after the record, it could not internally find the bucket causing an NPE. This is what i gathered from the bug.

**Comment by thiagotnunes** [comment]
@KiranmayiB is there any (manual) testing we can do for this (to simulate the bug and have the fix correct it)?

**Comment by thiagotnunes** [comment]
@KiranmayiB @ansh0l any updates?

**Comment by rajatbhatta** [comment]
@thiagotnunes: We shared the jar with the changes in this PR with the end user, and they confirmed that they're not facing the issue anymore. They're waiting for an official release to be available to use it. I think we can merge this PR.

**Comment by thiagotnunes** [comment]
Sounds good, thanks for checking!

**Review by thiagotnunes — APPROVED** [review]

**Pull request merged**
