### PR TITLE
fix: respect PDML timeout when using streaming RPC

### LINKED ISSUE #336: PDML Timeout not Respected
When using PDML for long running tasks (> 1 hour) the task fails after one hour with a deadline exceeded exception (`Exception in thread "main" com.google.cloud.spanner.SpannerException: DEADLINE_EXCEEDED: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 3599.998701666s.`). 

Note that by default the timeout should be 2 hours:
https://github.com/googleapis/java-spanner/blob/45acd8960c961d48e91a7b1546efa64d9e9ae576/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java#L313 

This is however not respected and overriden by the RPC timeout configured, which by default is 1 hour:

https://github.com/googleapis/googleapis/blob/50ae1c72fd94a3ae4269394b09e4b7fbb9251146/google/spanner/v1/spanner_grpc_service_config.json#L14

#### Steps to reproduce

  1. Create a default spanner client.
  2. Run a PDML update task that takes more than 1 hour. I have created a table with > 1 billion records to reproduce the problem.

#### Code example

```java
final SpannerOptions options = SpannerOptions.newBuilder().build();
final Spanner spanner = options.getService();
final DatabaseId id = DatabaseId.of("project", "instance", "database");
final DatabaseClient client = spanner.getDatabaseClient(id);

// This times out after 1 hour with a DeadlineExceededException
client.executePartitionedUpdate(Statement.of(
    "UPDATE Table SET Column = 'Value' WHERE true"
));
```

#### Stack trace
```
Exception in thread "main" com.google.cloud.spanner.SpannerException: DEADLINE_EXCEEDED: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 3599.998701666s. [buffered_nanos=115604067, remote_addr=spanner.googleapis.com/142.250.67.10:443]
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:211)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:57)
	at com.google.cloud.spanner.SpannerExceptionFactory.fromApiException(SpannerExceptionFactory.java:226)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:144)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:94)
	at com.google.cloud.spanner.PartitionedDMLTransaction.executeStreamingPartitionedUpdate(PartitionedDMLTransaction.java:156)
	at com.google.cloud.spanner.SessionImpl.executePartitionedUpdate(SessionImpl.java:118)
	at com.google.cloud.spanner.SessionPool$PooledSession.executePartitionedUpdate(SessionPool.java:1349)
	at com.google.cloud.spanner.SessionPool$PooledSessionFuture.executePartitionedUpdate(SessionPool.java:1236)
	at com.google.cloud.spanner.DatabaseClientImpl$3.apply(DatabaseClientImpl.java:227)
	at com.google.cloud.spanner.DatabaseClientImpl$3.apply(DatabaseClientImpl.java:224)
	at com.google.cloud.spanner.DatabaseClientImpl.runWithSessionRetry(DatabaseClientImpl.java:241)
	at com.google.cloud.spanner.DatabaseClientImpl.executePartitionedUpdate(DatabaseClientImpl.java:222)
	at com.google.cloud.sample.app.pdml.dao.UserDao.activateUsers(UserDao.java:61)
	at com.google.cloud.sample.app.pdml.PdmlApp.main(PdmlApp.java:17)
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 3599.998701666s. [buffered_nanos=115604067, remote_addr=spanner.googleapis.com/142.250.67.10:443]
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at com.google.api.gax.grpc.GrpcDirectStreamController$ResponseObserverAdapter.onClose(GrpcDirectStreamController.java:149)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.cloud.spanner.spi.v1.SpannerErrorInterceptor$1$1.onClose(SpannerErrorInterceptor.java:100)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$1CloseInContext.runInContext(ClientCallImpl.java:416)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

#### Any additional information below
It seems that the following is happening:

- By default we set the `streamWaitTimeout` to 2 hours in the context for the gRPC call.
- By default we set the `streamIdleTimeout` to 30 mins in the context for the gRPC call.
- By default we set the `timeout` to null in the context for the gRPC call.
- During the call to the gRPC endpoint we merge the read context with a default read context, which changes the value of the `timeout` to 1 hour.
- The PDML change fails after 1 hour (not 2 hours) with a deadline exceeded exception, according to the `timeout` variable set.

I am not sure where the `streamWaitTimeout` and `streamIdleTimeout` values are used.

I think that we would need to set the also the `timeout` value based on the `partitionedDmlTimeout` for PDML executions.

### PR DESCRIPTION
**Pull request by olavloite**
@thiagotnunes Would you mind trying the same test with this PR? I don't have a dataset that is big enough that it will run for more than one hour.

Fixes #336

### CODE REVIEW

**Comment by thiagotnunes** [comment]
@olavloite will do so on Monday and will let you know.

Digging in a little on the fix, it seems we just needed to fix the keepalive for the rpc calls, so am I right to assume that the thinking is that the `streamWaitTimeout` is the one being respected for this particular call?

Thanks for looking into this!

**Comment by thiagotnunes** [comment]
I got another exception when running the code. I think there is a bug on using the `remainingTimeout` (line 108)  on the `PartitionedDMLTransaction`. If the timeout is `<= 0`, we do not cancel the retry. A simple fix would be to `break` in this case. Below is the stack trace:

```java
Exception in thread "main" com.google.cloud.spanner.SpannerException: UNKNOWN: Invalid timeout: < 0 s
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:211)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:57)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:151)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:94)
	at com.google.cloud.spanner.PartitionedDMLTransaction.executeStreamingPartitionedUpdate(PartitionedDMLTransaction.java:156)
	at com.google.cloud.spanner.SessionImpl.executePartitionedUpdate(SessionImpl.java:118)
	at com.google.cloud.spanner.SessionPool$PooledSession.executePartitionedUpdate(SessionPool.java:1349)
	at com.google.cloud.spanner.SessionPool$PooledSessionFuture.executePartitionedUpdate(SessionPool.java:1236)
	at com.google.cloud.spanner.DatabaseClientImpl$3.apply(DatabaseClientImpl.java:227)
	at com.google.cloud.spanner.DatabaseClientImpl$3.apply(DatabaseClientImpl.java:224)
	at com.google.cloud.spanner.DatabaseClientImpl.runWithSessionRetry(DatabaseClientImpl.java:241)
	at com.google.cloud.spanner.DatabaseClientImpl.executePartitionedUpdate(DatabaseClientImpl.java:222)
	at com.google.cloud.spanner.PdmlIssue.main(PdmlIssue.java:14)
Caused by: java.lang.IllegalArgumentException: Invalid timeout: < 0 s
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
	at com.google.api.gax.grpc.GrpcCallContext.withStreamWaitTimeout(GrpcCallContext.java:177)
	at com.google.cloud.spanner.spi.v1.GapicSpannerRpc.executeStreamingPartitionedDml(GapicSpannerRpc.java:1108)
	at com.google.cloud.spanner.PartitionedDMLTransaction.executeStreamingPartitionedUpdate(PartitionedDMLTransaction.java:113)
	... 8 more
```

This is my executor:

```java
final SpannerOptions options = SpannerOptions.newBuilder().build();
final Spanner spanner = options.getService();
final DatabaseId id = DatabaseId.of(PROJECT, INSTANCE, DATABASE);
final DatabaseClient client = spanner.getDatabaseClient(id);

client.executePartitionedUpdate(Statement.of(
    "UPDATE Table SET bool = true WHERE true"
));
```

**Comment by thiagotnunes** [comment]
In any case, the failure occurs after the specified timeout (2 hours by default).

**Comment by olavloite** [comment]
@thiagotnunes Thanks for the test results. I've updated the retry-loop to take a potential zero or negative deadline into account, and I've added some additional unit tests for this class. PTAL.

**Comment by thiagotnunes** [comment]
I know what the problem is: multiple failures are occurring so whenever we are subtracting the elapsed time, we are subtracting the accumulated time of the `stopWatch` every time. In order to fix this, we should reset the `stopWatch` in the case that we are about to retry. We could add `stopWatch.reset()` when catching the `UnavailableException` and inside the if statement (after line 135 of the `PartitionedDMLTransaction).

An example of the problem I am seeing:
1. We start the PDML statement.
```
stopWatch = "PT0S"
remainingTimeout = "PT2H"; 
```
2. After 10 mins there is a retry-able failure. We subtract the `stopWatch` from the `remainingTimeout`.
```
stopWatch = "PT10M";
remainingTimeout = remainingTimeout - stopWatch = "PT1H50M";
```
3. After 20 mins from the start (1) there is another failure. We again subtract the `stopWatch` from the `remainingTimeout`, but instead of subtracting 10 mins (time elapsed from the first retry to the second retry), we subtract 20 mins (time elapsed from the start to the second retry).
```
stopWatch = "PT20M"
remainingTimeout = remainingTimeout - stopWatch = "PT1H30M"; // This should had been PT1H40M
```

Btw, @olavloite let me know if you this feedback loop is too big (me testing a day after your change). I could implement these minor fixes if you'd like so, otherwise I am happy on testing / reporting back the results to you.

**Comment by olavloite** [comment]
@thiagotnunes Thanks for the elaborate testing and report. Hopefully the timeout problem should be fixed now.

And yes, please do feel free to add any additional fixes that might be needed to get this 100%.

**Pull request merged**
