### PR TITLE
chore: fix kokoro windows java 8 ci by setting JAVA11_HOME env variable

### PR DESCRIPTION
**Pull request by mpeddada1**
Related to #2205

### CODE REVIEW

**Comment by mpeddada1** [comment]
JAVA11_HOME which is used to compile classes in JDK 11 for GraalVM doesn't appear to be set for the java8-win job
```
Verify if JAVA11_HOME is set *************

```

**Comment by mpeddada1** [comment]
```
JAVA11_HOME="/usr/lib/jvm/java-11-openjdk-amd64" (No matching key in allowed env vars)
JAVA8_HOME="/usr/local/openjdk-8" (No matching key in allowed env vars)
```

**Comment by mpeddada1** [comment]
https://github.com/googleapis/java-spanner/pull/2207/commits/d9eb102b1c00d370491636e7cfc4079a8ad17c2c resulted in successful build

**Review by rajatbhatta — APPROVED** [review]
LGTM. 
Thanks for working on this, @mpeddada1! :)

**Pull request merged**
